# Generated by Django 4.1 on 2022-09-02 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product')},
        ),
    ]
