# Generated by Django 4.1 on 2022-09-04 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_productrating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user_id', 'product_id')},
        ),
    ]
